# S3 Endpoint Configuration
endpoint_url: 'https://eodata.dataspace.copernicus.eu'
endpoint_stac: 'https://stac.dataspace.copernicus.eu/v1/'
bucket_name: 'eodata'

bands:
  - 'B02'
  - 'B03'
  - 'B04'

# Query Configuration
query:
  bbox:
    - 3.28
    - 45.38
    - 11.2
    - 50.18

  start_date: '2026-01-01'
  end_date: '2026-01-20'

  max_items: 1000
  max_cloud_cover: 30

